import os
import shutil
import tempfile
from typing import List
from fastapi import APIRouter, UploadFile, File, HTTPException, Body
from fastapi.responses import FileResponse
from pydantic import BaseModel
from backend.documents.pyq_ingestion import ingest_pyq
from backend.documents.pyq_matcher import get_coverage_matrix
from backend.documents.paper_generator import generate_paper, PaperConfig, SectionConfig
from backend.documents.models import Document
from backend.documents.ingestion import process_document
from backend.documents.converter import convert_docx_to_pdf
from django.core.files.base import ContentFile

router = APIRouter()

class SectionConfigSchema(BaseModel):
    type: str
    marks_per_q: int
    count: int

class PaperConfigSchema(BaseModel):
    title: str
    total_marks: int = 100
    sections: List[SectionConfigSchema]
    prefer_recent: bool = True
    cover_all_outcomes: bool = True
    syllabus_id: str

@router.post("/upload")
async def upload_pyq(file: UploadFile = File(...)):
    """
    Uploads a PYQ PDF, saves it temporarily, and runs the ingestion pipeline.
    """
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported.")
    
    # Save to a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name
        
    try:
        # Run ingestion logic
        # Note: ingest_pyq prints count, so we might need it to return count for the API
        # I'll assume I can modify it or it returns something.
        # For now, we'll just run it and return a success message.
        # (In a real scenario, I'd update ingest_pyq to return the count)
        ingest_pyq(tmp_path)
        return {"message": "Processing started", "filename": file.filename}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

@router.post("/upload-batch")
async def upload_batch(
    handout_file: UploadFile = File(...),
    pyq_files: List[UploadFile] = File(...)
):
    """
    Simultaneously ingests a syllabus/handout and multiple PYQ files for Smart Paper Mode.
    """
    # 1. Store local temp paths for cleanup
    temp_paths = []
    syllabus_id = None
    total_q = 0

    try:
        # A. Process Handout (Detect & Convert Word)
        content = await handout_file.read()
        target_name = handout_file.filename
        
        if target_name.endswith('.docx'):
            pdf_path = convert_docx_to_pdf(content)
            if pdf_path:
                with open(pdf_path, 'rb') as f:
                    content = f.read()
                target_name = target_name.replace('.docx', '.pdf')
                temp_paths.append(pdf_path) # Track for cleanup

        doc = Document.objects.create(
            title=target_name,
            file=ContentFile(content, name=target_name)
        )
        
        # Trigger standard ingestion logic
        success = process_document(doc.id)
        if not success:
            raise HTTPException(status_code=500, detail="Handout ingestion protocol failed.")
        
        syllabus_id = str(doc.id)

        # B. Process PYQ Files
        for file in pyq_files:
            if not (file.filename.endswith(".pdf") or file.filename.endswith(".docx")):
                continue
            
            # Read content once
            q_content = await file.read()
            
            if file.filename.endswith(".docx"):
                tmp_path = convert_docx_to_pdf(q_content)
                if not tmp_path: continue
            else:
                # Save to temporary path for the pyq_ingestion logic
                with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                    tmp.write(q_content)
                    tmp_path = tmp.name
            
            temp_paths.append(tmp_path)
            
            try:
                # Run vectorized ingestion
                count = ingest_pyq(tmp_path)
                total_q += (count or 0)
            except Exception as e:
                print(f"Warning: Failed to ingest PYQ {file.filename}: {e}")
                continue

        return {
            "syllabus_id": syllabus_id,
            "pyq_count": len(pyq_files),
            "question_count": total_q
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Mission Failed: {str(e)}")
        
    finally:
        # 4. Neural Cleanup Protocol
        for path in temp_paths:
            if os.path.exists(path):
                os.remove(path)

@router.post("/demo")
async def process_demo_mission():
    """
    Seeds a demo environment using pre-stored assets in demo_assets/.
    """
    # Files are generated by generate_demo.py into demo_assets/
    demo_dir = os.path.join(os.getcwd(), "demo_assets")
    handout_path = os.path.join(demo_dir, "demo_handout.pdf")
    pyq_paths = [
        os.path.join(demo_dir, "demo_pyq_2022.pdf"),
        os.path.join(demo_dir, "demo_pyq_2023.pdf")
    ]

    # Quick validation
    if not os.path.exists(handout_path):
        raise HTTPException(status_code=404, detail="Demo assets not found. Run generate_demo.py first.")

    try:
        # 1. Process Handout (Django Ingestion)
        with open(handout_path, 'rb') as f:
            content = f.read()
            doc = Document.objects.create(
                title="DEMO: Neural Networks 101",
                file=ContentFile(content, name="demo_handout.pdf")
            )
        
        # Trigger standard ingestion logic
        success = process_document(doc.id)
        if not success:
            raise HTTPException(status_code=500, detail="Demo handout ingestion failed.")
        
        syllabus_id = str(doc.id)

        # 2. Process PYQ Files
        total_q = 0
        for path in pyq_paths:
            try:
                # ingest_pyq is a synchronous function that handles DB connection itself
                count = ingest_pyq(path)
                total_q += (count or 0)
            except Exception as e:
                print(f"Warning: Demo PYQ {path} failed: {e}")
                continue

        return {
            "syllabus_id": syllabus_id,
            "pyq_count": len(pyq_paths),
            "question_count": total_q,
            "is_demo": True
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Demo Mission Initialization Failed: {str(e)}")

@router.get("/coverage")
async def get_coverage(syllabus_id: str):
    """
    Returns the coverage matrix and a summary for a given syllabus.
    """
    matrix = get_coverage_matrix(syllabus_id)
    if not matrix:
        return {"summary": {"total_outcomes": 0, "covered": 0, "blind_spots": 0, "high_freq_count": 0}, "matrix": {}}
        
    total_outcomes = len(matrix)
    blind_spots = sum(1 for m in matrix.values() if m.get("blind_spot"))
    covered = total_outcomes - blind_spots
    high_freq_count = sum(1 for m in matrix.values() if m.get("high_freq"))
    
    return {
        "summary": {
            "total_outcomes": total_outcomes,
            "covered": covered,
            "blind_spots": blind_spots,
            "high_freq_count": high_freq_count
        },
        "matrix": matrix
    }

@router.post("/generate")
async def generate_exam_paper(config: PaperConfigSchema):
    """
    Generates a PDF exam paper based on the provided configuration.
    """
    # Convert Pydantic schema to the dataclass expected by paper_generator
    sections = [SectionConfig(type=s.type, marks_per_q=s.marks_per_q, count=s.count) for s in config.sections]
    paper_config = PaperConfig(
        title=config.title,
        total_marks=config.total_marks,
        sections=sections,
        prefer_recent=config.prefer_recent,
        cover_all_outcomes=config.cover_all_outcomes
    )
    
    pdf_path = generate_paper(paper_config, config.syllabus_id)
    
    if not pdf_path or not os.path.exists(pdf_path):
        raise HTTPException(status_code=500, detail="Failed to generate PDF paper.")
        
    return FileResponse(
        pdf_path, 
        media_type="application/pdf", 
        filename=os.path.basename(pdf_path),
        headers={"Content-Disposition": f"attachment; filename={os.path.basename(pdf_path)}"}
    )
