# Generated by Django 6.0.2 on 2026-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
