# Generated by Django 6.0.2 on 2026-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generated_lecture_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
