# Generated by Django 6.0.2 on 2026-04-12 19:25

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_generated_lecture_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('source_paper', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('question_number', models.CharField(max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
            ],
            options={
                'unique_together': {('source_paper', 'question_number')},
            },
        ),
    ]
